chat-space チャット画面実装　メインチャッのヘッダー実装
mayu0506/chat-space pull request #7
Opened 2019-04-12 10:01 UTC by mayu0506

# What
チャット画面のヘッダーを実装

# Why
チャット画面に必須機能なため
終了後、チャットメッセージ画面作成のため

<img width="1440" alt="chatspace_メインチャット画面_ヘッダー" src="https://user-images.githubusercontent.com/49383851/56029377-32f48600-5d55-11e9-97bb-4689f42e3fe4.png">

2019-04-12 10:11 UTC, katsu105 reviewed
application.scssは@importだけにして、別ファイルでscssを記述するようにしましょう。
application.html.hamlに記述するのではなく、group#indexに記述し、必要であれば部分テンプレートに記述してください。

2019-04-14 05:01 UTC, mayu0506 commented
以下のように修正しました。

# 1
assets/stylesheetsに新しくstyle.scssを作り、@import以外はそこに記述する。
# 2
views/application.html.hamlには左のメニュー画面だけ記述
# 3
views/groups/index.html.hamlには一番上に表示されるグループ名部分表示

2019-04-14 05:06 UTC, hiroki5123 commented
テキストフォームの部分が確認できないのですが、実装していないのであれば実装してください。

2019-04-14 05:06 UTC, ghost requested changes

2019-04-14 05:06 UTC, hiroki5123 commented on app/assets/stylesheets/application.scss
> + */
ここから上は削除してください

2019-04-14 05:06 UTC, hiroki5123 commented on app/views/groups/index.html.haml
> +      %a{href:'/groups/id/edit'}
link_toで仮置きしておきましょう

2019-04-14 06:52 UTC, mayu0506 commented on app/views/groups/index.html.haml
> +      %a{href:'/groups/id/edit'}
= link_toを使って仮置きしました。

テキストフォーム部分を作り部分テンプレートとしました。

2019-04-14 06:53 UTC, mayu0506 commented on app/assets/stylesheets/application.scss
> + */
修正しました。

2019-04-14 06:58 UTC, hiroki5123 commented on app/views/groups/index.html.haml
> +      %a{href:'/groups/id/edit'}
テキストフォームが貼っていただいた画像にないのですが。。。

2019-04-14 10:53 UTC, merged